version: '2.0'

services:
  terraform:
    image: hashicorp/terraform:0.9.2
    working_dir: /workdir/${PROVIDER}
    environment:
      # amazon
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

      # azure
      ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
      ARM_CLIENT_ID: ${ARM_CLIENT_ID}
      ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
      ARM_TENANT_ID: ${ARM_TENANT_ID}

      # google
      GOOGLE_CREDENTIALS: /root/terraform.json
      GOOGLE_PROJECT: ${GOOGLE_PROJECT}
      GOOGLE_REGION: ${GOOGLE_REGION}
    volumes:
      - ${GOOGLE_CREDENTIALS}:/root/terraform.json
      - ${HOME}/.ssh:/root/.ssh
      - .:/workdir

